#!/usr/bin/env node
// Verifies App Store listing limits and trademark hygiene, then writes store/LISTING.md.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const l = JSON.parse(readFileSync(join(root, 'store', 'listing.json'), 'utf8'));
const len = (s) => [...s].length;

const LIMITS = {
  name: [2, 30],
  subtitle: [0, 30],
  promotionalText: [0, 170],
  keywords: [0, 100],
  description: [10, 4000],
  whatsNew: [0, 4000],
  'iap.displayName': [1, 35],
  'iap.description': [1, 55],
};
const get = (k) => k.split('.').reduce((o, p) => o?.[p], l) ?? '';

// Third-party marks that must not appear in name, subtitle or keywords (Guideline 5.2.1).
const TRADEMARKS = [
  'apple', 'iphone', 'ipad', 'ios', 'icloud', 'face id', 'vision', 'adobe', 'acrobat', 'camscanner', 'genius scan',
  'scanner pro', 'readdle', 'microsoft', 'word', 'excel', 'google', 'dropbox', 'docusign', 'evernote', 'notarize', 'turbo',
];
const errors = [];
const rows = [];
for (const [k, [min, max]] of Object.entries(LIMITS)) {
  const v = get(k);
  const n = len(v);
  const ok = n >= min && n <= max;
  if (!ok) errors.push(`${k} is ${n} characters (allowed ${min}-${max}).`);
  rows.push([k, n, max, ok]);
}
for (const k of ['name', 'subtitle', 'keywords']) {
  const v = get(k).toLowerCase();
  for (const tm of TRADEMARKS) {
    if (new RegExp(`(^|[^a-z])${tm}([^a-z]|$)`).test(v)) errors.push(`${k} contains third-party mark "${tm}".`);
  }
}
const kw = l.keywords.split(',');
if (kw.some((k) => k !== k.trim() || !k)) errors.push('keywords must be comma-separated with no spaces or empty items.');
const nameWords = `${l.name} ${l.subtitle}`.toLowerCase().split(/[^a-z0-9]+/);
const dup = kw.filter((k) => nameWords.includes(k.toLowerCase()));
if (dup.length) errors.push(`keywords repeat words already in name/subtitle: ${dup.join(', ')}`);

const md = `# App Store listing (en-US)

Generated by \`node scripts/check-listing.mjs\` from \`store/listing.json\`. Do not edit by hand.

| Field | Characters | Limit | OK |
| --- | ---: | ---: | :---: |
${rows.map(([k, n, max, ok]) => `| ${k} | ${n} | ${max} | ${ok ? '✅' : '❌'} |`).join('\n')}

## Name
${l.name}

## Subtitle
${l.subtitle}

## Promotional text
${l.promotionalText}

## Keywords
\`${l.keywords}\`

## Description
${l.description}

## What's New
${l.whatsNew}

## URLs
- Support: ${l.supportUrl}
- Marketing: ${l.marketingUrl}
- Privacy policy: ${l.privacyPolicyUrl}

## Categories and rating
- Primary: ${l.primaryCategory}
- Secondary: ${l.secondaryCategory}
- Age rating: ${l.ageRating} (answer "None" to every content question)
- Copyright: ${l.copyright}

## In-app purchase
| Field | Value |
| --- | --- |
${Object.entries(l.iap).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

## App Privacy
Data Not Collected. (Apple processes in-app purchase payments; that does not count as developer collection.)
`;
writeFileSync(join(root, 'store', 'LISTING.md'), md);
for (const [k, n, max, ok] of rows) console.log(`${ok ? '✓' : '✗'} ${k.padEnd(18)} ${String(n).padStart(4)} / ${max}`);
if (errors.length) {
  console.error(`\n${errors.map((e) => `✗ ${e}`).join('\n')}`);
  process.exit(1);
}
console.log('\nListing OK. Wrote store/LISTING.md');
